### PR TITLE
Add user cancelled error for restore purchase

### PR DESCRIPTION
**Pull request by cbrevik**
Simple change to make it obvious if user cancels login dialog when you try to restore purchases.

### CODE REVIEW

**Comment by chirag04** [comment]
@cbrevik we should unify how we handle error for purchaseProduct and restorePurchase.

Can you update the PR to do this: https://github.com/cbrevik/react-native-in-app-utils/blob/ae52ecfbf699f1ddf3f4a52514184eedaad761ae/InAppUtils/InAppUtils.m#L38

You can check in js if error was for cancel or something else.

**Comment by cbrevik** [comment]
@chirag04 sure I could do that. But I just tested it, and the error is sort of unintuitive when translated to JS with that method:

image

The only difference between error-codes is the integer behind `ESKERRORDOMAIN`. The `2` in this case means cancelled.

Maybe instead we could implement `RCTJSErrorFromCodeMessageAndNSError(NSString *code,  NSString *message, NSError *__nullable error)` and return a better error code?

Also, at the moment it returns a `restore_failed` string, which wouldn't be backwards-compat with that translation if people check that code.

**Comment by ryancoughlin** [comment]
Merge? 🙏

**Comment by chirag04** [comment]
sorry for the delay guys and thanks for the PR @cbrevik

**Comment by chirag04** [comment]
It would be awesome if we can document this somewhere

**Comment by ryancoughlin** [comment]
Great, thank you both.

**Comment by ryancoughlin** [comment]
Actually, would this https://github.com/chirag04/react-native-in-app-utils/issues/89 be solved by this PR?

**Comment by cbrevik** [comment]
@chirag04 Thanks man.

@ryancoughlin This PR is just for handling cancel of the login dialog when restoring products. If there is a cancel when buying a product, then will most likely be [handled here](https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L38). I haven't had the issue described in #89. 

Maybe `transaction` or `transaction.error`  contains a `code` which can be easily translated like with this PR?

**Comment by cbrevik** [comment]
Looks like `transaction.error.code` might use the same error codes as I translate from here in this PR. 

Maybe add a static c function to translate from the `code`:

```obj-c
static NSString *translateErrorCode(NSInteger code, NSString* defaultError)
{
    switch (code)
    {
        case SKErrorPaymentCancelled:
            return @"user_cancelled";
        default:
            return defaultError;
    }
}
```

And use in all error cases:
```obj-c
- (void)paymentQueue:(SKPaymentQueue *)queue
restoreCompletedTransactionsFailedWithError:(NSError *)error
{
    NSString *key = RCTKeyForInstance(@"restoreRequest");
    RCTResponseSenderBlock callback = _callbacks[key];
    if (callback) {
        callback(@[translateErrorCode(error.code, @"restore_failed")]);
        
    (...)
}
```

```obj-c
- (void)paymentQueue:(SKPaymentQueue *)queue
 updatedTransactions:(NSArray *)transactions
{
    for (SKPaymentTransaction *transaction in transactions) {
        switch (transaction.transactionState) {
            case SKPaymentTransactionStateFailed: {
                NSString *key = RCTKeyForInstance(transaction.payment.productIdentifier);
                RCTResponseSenderBlock callback = _callbacks[key];
                if (callback) {
                    callback(@[translateErrorCode(transaction.error.code, @"unknown_error")]);
    (...)
}
```

```obj-c
- (void)request:(SKRequest *)request didFailWithError:(NSError *)error{
    NSString *key = RCTKeyForInstance(request);
    RCTResponseSenderBlock callback = _callbacks[key];
    if(callback) {
        callback(@[translateErrorCode(error.code, @"unknown_error")]);
        [_callbacks removeObjectForKey:key];
    }
}
```

**Comment by cbrevik** [comment]
The above is completely untested, and I can't find any docs to see if you assumption about the `code` being the same everywhere. Just an idea.

**Comment by chirag04** [comment]
@cbrevik that's a good idea if somebody wants to send a PR 👍

**Comment by ryancoughlin** [comment]
That's what got me thinking about that. It does appear to come from that same transaction type, it's just handled in an odd manor now triggering a breaking error. 

I can try that out locally now.

**Comment by ryancoughlin** [comment]
I opened a WIP PR here: https://github.com/chirag04/react-native-in-app-utils/pull/104

Would love some thoughts when you have time.

**Pull request merged**
