### PR TITLE
Update to add every error and fix missed use cases

### LINKED ISSUE #15: Better error/fail handling
Hey, awesome work here!

In my fork (branch stranger) I added this to get more information at failing time. Otherwise if the user cancel or something else happen, I can't hide HUDs or react in the UI in any way.

```objc
switch (transaction.error.code) {
    case SKErrorUnknown:
        callback(@[@"transaction_failed_unknown"]);
        break;
    case SKErrorClientInvalid:
        callback(@[@"transaction_failed_client_invalid"]);
        break;
    case SKErrorPaymentCancelled:
        callback(@[@"transaction_failed_payment_cancelled"]);
        break;
    case SKErrorPaymentInvalid:
        callback(@[@"transaction_failed_payment_invalid"]);
        break;
    case SKErrorPaymentNotAllowed:
        callback(@[@"transaction_failed_payment_not_allowed"]);
        break;
    case SKErrorStoreProductNotAvailable:
        callback(@[@"transaction_failed_store_product_not_available"]);
        break;
    case SKErrorCloudServicePermissionDenied:
        callback(@[@"transaction_failed_cloud_service_permission_denied"]);
        break;
    case SKErrorCloudServiceNetworkConnectionFailed:
        callback(@[@"transaction_failed_cloud_service_network_connection_failed"]);
        break;

    default:
        break;
}
```

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
Dear @chirag04,

Thank you for your work. Please merge this PR to close #15 finally and as alternative to move forward the suspended PR in https://github.com/chirag04/react-native-in-app-utils/pull/21.

Kind regards,
Denis

### CODE REVIEW

**Comment by chirag04** [comment]
LGTM. This is a breaking change tho. `SKErrorPaymentCancelled` is now going to be an error in javascript. Users needs to handle this in javascript now.  Can you also document this in the readme?


cc @grabbou

**Comment by grabbou** [comment]
LGTM.

**Comment by DenisIzmaylov** [comment]
It seemed to me there is nothing to update. :)```
var productIdentifier = 'com.xyz.abc';
InAppUtils.purchaseProduct(productIdentifier, (error, response) => {
   if(response && response.productIdentifier) {
      AlertIOS.alert('Purchase Successful', 'Your Transaction ID is ' + response.transactionIdentifier);
      //unlock store here.
   }
});
```

**Comment by chirag04** [comment]
can you not bump the version in package.json? we should be doing `3.0` instead of `2.4`.

**Comment by DenisIzmaylov** [comment]
Of course, no problem.

**Comment by chirag04** [comment]
thanks @DenisIzmaylov & @grabbou 

released v3.0.0 on npm.

**Comment by DenisIzmaylov** [comment]
Great! 👍

**Pull request merged**
