### PR TITLE
In-app purchases promotion

### LINKED ISSUE #178: iOS In-app purchases promotion
Is there any plan to integrate this new iOS feature?
https://developer.apple.com/app-store/promoting-in-app-purchases/

I need to implement it for my app so probably I'll do a PR when it's ready.

### PR DESCRIPTION
**Pull request by fluiddot**
I've added some functionality to the library to support the new feature of the in-app purchases promotion. Basically I added a couple of functions to get the promoted product and to trigger the purchase.

The most special part is how you get notified when the app is opened from a promoted product, I solved this by implementing `RCTEventEmitter` in the class.

Closes #178

### CODE REVIEW

**Comment by philwilks** [comment]
Hey @fluiddot thanks for your work on this. Are you using this modification in production?

**Comment by fluiddot** [comment]
@philwilks yeah, we released this a couple of weeks ago in our app

**Comment by melihmucuk** [comment]
any news?

**Comment by clementinoux** [comment]
Any merge on the roadmap ? @chirag04 @philwilks
Thanks guys !

**Comment by punjasin** [comment]
when it gonna be merge @chirag04 i use it for 2-3 month now but it lack of update another function so i want it to be with release versions

**Comment by karapish** [comment]
Seems like a useful functionality to have

**Pull request closed without merging**
