### PR TITLE
Add manual purchase finish

### PR DESCRIPTION
**Pull request by lunarraid**

### CODE REVIEW

**Comment by lazyhoneyant** [comment]
@lunarraid Why do you close this PR? I use your PR well. Is there any problem on this PR?

**Comment by lunarraid** [comment]
This PR was made in error. I meant to pull the change into the master branch of my fork only, as this change breaks compatibility with the main repo.

**Comment by lazyhoneyant** [comment]
@lunarraid I understand. I've used this PR to my fork repo. Thanks for sharing your useful code.

**Comment by Jacse** [comment]
@lunarraid this is extremely useful and necessary for the library. Do you think you could be convinced to merge your functionality into the lib?

**Comment by lunarraid** [comment]
I have no problem with re-opening this if the maintainer is cool with the breaking changes.

**Comment by chirag04** [comment]
I'm fine with making a breaking change. Refer the thread here: https://github.com/chirag04/react-native-in-app-utils/issues/124#issue-262259337

**Comment by lunarraid** [comment]
https://github.com/chirag04/react-native-in-app-utils/pull/135 has been opened.

**Pull request closed without merging**
