### PR TITLE
fix crash when originalTransactionId is null

### PR DESCRIPTION
**Pull request by philipshurpik**
Checking that originalTransaction is not null before restoring subscription

fixes issue #36

### CODE REVIEW

**Comment by codler** [comment]
Hope this will be merged

**Comment by philipshurpik** [comment]
@chirag04 Hi! :)
Would really appreciate if you can look at this pull request

**Comment by chirag04** [comment]
@philipshurpik sorry for the delay. can you rebase?

**Comment by chirag04** [comment]
going to close in favour of https://github.com/chirag04/react-native-in-app-utils/pull/78

**Pull request closed without merging**
