### PR TITLE
Expose transaction receipt

### PR DESCRIPTION
**Pull request by pennersr**
I would like to validate receipts on a per purchase basis. This PR exposes the transaction receipt as a base64 encoded string. 

Not sure, but this might be what @a-koka was after in issue #57 as well...

### CODE REVIEW

**Comment by a-koka** [comment]
Thanks for making note of my ask @pennersr. My question if mostly due to my lack of experience when it comes to dealing with the App Store and receipts.

I noticed that the base64 encoded string changes depending on when `validateReceipt` is called ie. A different string for before the transaction, after the transaction and yet another string if lets say we try it the day after.

I've been able to use all receipts successfully and wasn't sure if it matters when the receipt is persisted in the backend. In my head it makes sense to have one unique receipt per transaction very much like in real life and along the lines of what you are proposing with your PR.

**Comment by chirag04** [comment]
cc @sibelius thoughts?

**Comment by pennersr** [comment]
Perhaps a bit of background: I am in the process of moving a Cordova based app to RN.  Previously, it was using a Cordova plugin for IAP that exposed the transaction receipt:

https://github.com/j3k0/cordova-plugin-purchase/blob/374fa2b0d0eb38c31f046b00371e17679bcc0246/src/ios/InAppPurchase.m#L444

This receipt is currently missing from your project, hence the PR. It is needed to validate the purchase (per transaction) on the backend.

**Comment by sibelius** [comment]
@pennersr can't u validate the receipt like this: https://github.com/chirag04/react-native-in-app-utils/issues/25#issuecomment-242503549

@chirag04 I think more information exposed in the bridge is not a bad idea

**Comment by pennersr** [comment]
@sibelius For me, that would be suboptimal:

- The backend API requires a transaction receipt per parcel (so I really need to hand these over)

- The validation you pointed to requires one more roundtrip/callback, whereas in my PR the receipts are available immediately.

- The PR simply exposes an official iOS property (transactionReceipt)

- The property is exposed in other systems as well (e.g. Cordova).

All in all, I cannot see any disadvantage in merging this PR...

**Comment by kesha-antonov** [comment]
@chirag04 Hey man! Need it too! Please merge!

**Comment by chirag04** [comment]
sorry for the delay guys. I was on vacation.

**Pull request merged**
